// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MZPlus","status":true,"description":"<MZPlus> Based off Quasi's amazing QPlus Core.","parameters":{"Quick Test":"false"}},
{"name":"MZPlusQuickStart","status":false,"description":"<MZPlusQuickStart> Skips the title for fast testing. (Will only skip the title in dev mode).  Credit to Quasi.","parameters":{"Dev Mode Only":"true"}},
{"name":"MZPlusSmoothCamera","status":false,"description":"","parameters":{}}
];
